### PR TITLE
Add to Forensics Module

### PR DESCRIPTION
**Pull request by Jrotenberger**
Memory Imaging, Volatile and Non-Volatile Data collection, User-Data
Collection, Network IP connection info and more!!!

### CODE REVIEW

**Comment by mwjcomputing** [comment]
Hey Jeff looks good so far. We need to make sure we have help. I will be diving into these over the next few days. But so far so good.

**Comment by ghost** [comment]
Jeff,

I like these. Like mwj said, we definitely need some help in the comment blocks for these. Also, functions like Get-SystemUpTime should probably go to Utility\ and not be directly in Forensics.

Otherwise, these look great!

**Comment by Jrotenberger** [comment]
Thanks!  That means a lot.  I'm going through now and adding more
documentation.  I'm totally OK putting scripts where ever it makes sense.

More is still coming too!

**Comment by ghost** [comment]
Jeff,

Opened issue https://github.com/PoshSec/PoshSec/issues/39.

**Comment by ghost** [comment]
Once that is fixed, it works like a champ! Check it out :)

psf_systemuptime

**Comment by Jrotenberger** [comment]
Sweet....some of the forensic stuff is wonked...the scripts are pulling
some data from local host and some from target...crud.

**Pull request merged**
